;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<AppWindow>>>;;;
[AppWindow]
DpiWindowSizeFactor=1.5
WindowPosition=376,219
WindowSize=1920,1020
;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=207,48
Size=177,177
Collapsed=0

[Window][Modal]
Pos=179,182
Size=368,215
Collapsed=0

[Window][Camera_window]
Pos=60,60
Size=824,693
Collapsed=0

[Window][Camera config]
ViewportPos=2882,131
ViewportId=0xD420C146
Size=731,761
Collapsed=0

[Window][Technical documents##Window]
ViewportPos=64,259
ViewportId=0x6999A888
Size=2203,959
Collapsed=0

[Window][StatusBar]
Pos=0,961
Size=1920,58
Collapsed=0

[Table][0x4608C4EA,1]
Column 0  Weight=1.0000

[Docking][Data]

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
